class Transfer_Locators(object):
    TRANSFER_LINK_LOCATOR = "//div[@routerlink='/transfer']"
    TRANSFER_BET_ACCOUNTS_LOCATOR = "//div[@ng-reflect-router-link='admin/transfer-between-account']"
    SELECT_USER_LOCATOR = "//ng-select[@ng-reflect-placeholder='Select a user']"
    ACCOUNT_FROM_LOCATOR = "//app-account-select[@ng-reflect-name='accountFrom']"
    ACCOUNT_TO_LOCATOR = "//app-account-select[@ng-reflect-name='accountTo']"
    AMOUNT_LOCATOR = "//input[@formcontrolname='outgoingAmount']"
    DESCRIPTION_LOCATOR = "textarea#description"
    CONTINUE_BUTTON_LOCATOR = "//button[@type='submit']"
    CONFIRM_BUTTON_LOCATOR = "//button[@type='submit']"
    SUCCESS_LOCATOR = "div.success-popup"
